context:
  name: esssans
  version: 25.6.0
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/esssans-${{ version }}.tar.gz
  sha256: 0aca5c8a673d19083662862f03c9d7827637f2576585a9b4ceb975961167d3a9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }} 
    - dask-core
    - python-graphviz
    - essreduce >=25.02.4
    - numpy
    - pandas
    - plopp
    - pythreejs
    - sciline >=25.04.1
    - scipp >=24.09.1
    - scippneutron >=25.02.1
    - scippnexus >=23.12.1

tests:
  - python:
      imports:
        - ess.sans
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: SANS data reduction for the European Spallation Source
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/esssans
  homepage: https://scipp.github.io/esssans/

extra:
  recipe-maintainers:
    - MridulS
